version: "3"
services:
  core-api:
    image: wwan13/deskmood-core-api:prod
    container_name: core-api
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - "./.env"
    volumes:
      - /home/ubuntu/deskmood/log:/log

  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../.platform/nginx/config:/etc/nginx/conf.d
      - ../.platform/nginx/certbot/conf:/etc/letsencrypt
      - ../.platform/nginx/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ../.platform/nginx/certbot/conf:/etc/letsencrypt
      - ../.platform/nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../.platform/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "$UID:$GID"
    ports:
      - "3010:3010"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./log:/log
      - ../.platform/promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml

volumes:
  grafana-data: