spring:
  profiles:
    active: dev
    include:
      - core-db
      - logging
      - monitoring
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB