spring:
  profiles:
    active: local
    include:
      - core-db
      - logging
      - monitoring
      - google-client
      - naver-client
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expired: ${ACCESS_TOKEN_EXPIRED}
  refresh-token-expired: ${REFRESH_TOKEN_EXPIRED}